spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tokyo
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
